---
- name: Gather system facts
  ansible.builtin.setup:

- name: Import monitoring installation tasks
  ansible.builtin.import_tasks: install.yml

- name: Import monitoring verification tasks
  ansible.builtin.import_tasks: verify.yml
