---
docker_apt_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_apt_key_path: /etc/apt/keyrings/docker.asc
docker_apt_key_mode: "0644"
docker_apt_keyring_dir: /etc/apt/keyrings
docker_keyring_dir_mode: "0755"
docker_repo_url: https://download.docker.com/linux/ubuntu
docker_repo_component: stable
docker_repo_filename: docker
docker_arch: amd64
docker_package_state: present
docker_service_name: docker
docker_users: []
docker_prerequisite_packages:
  - ca-certificates
  - curl
  - gnupg
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
