---
- name: Gather system facts
  ansible.builtin.setup:

- name: Import Helm installation tasks
  ansible.builtin.import_tasks: install.yml

- name: Import Helm verification tasks
  ansible.builtin.import_tasks: verify.yml
