---
- name: Gather system facts
  ansible.builtin.setup:

- name: Import Kind installation tasks
  ansible.builtin.import_tasks: install.yml

- name: Import Kind cluster tasks
  ansible.builtin.import_tasks: cluster.yml

- name: Import Kind verification tasks
  ansible.builtin.import_tasks: verify.yml
