---
- name: Gather system facts
  ansible.builtin.setup:

- name: Import common installation tasks
  ansible.builtin.import_tasks: install.yml

- name: Import common verification tasks
  ansible.builtin.import_tasks: verify.yml
