[all:vars]
ansible_user=ubuntu
ansible_become=true
ansible_become_method=sudo
ansible_python_interpreter=/usr/bin/python3

[skillpulse]
skillpulse01 ansible_host=13.51.54.60 ansible_ssh_private_key_file=~/.ssh/my-web-server-key.pem
