---
- name: Gather system facts
  ansible.builtin.setup:

- name: Import kubectl installation tasks
  ansible.builtin.import_tasks: install.yml

- name: Import kubectl verification tasks
  ansible.builtin.import_tasks: verify.yml
