---
argocd_namespace: argocd
argocd_release_name: argocd
argocd_chart_repo_name: argo
argocd_chart_repo_url: https://argoproj.github.io/argo-helm
argocd_chart_name: argo-cd
argocd_chart_version: "5.53.6"
argocd_create_namespace: true
argocd_wait_timeout: 600
argocd_supported_releases:
  - "jammy"
  - "noble"
  - "resolute"
kubeconfig_path: "/home/ubuntu/.kube/config"
gitops_repo_url: "https://github.com/yashpatle741/main-project-gitops.git"
gitops_branch: "main"
gitops_path: "k8s"
