---
- name: Gather system facts
  ansible.builtin.setup:

- name: Import ingress-nginx installation tasks
  ansible.builtin.import_tasks: install.yml

- name: Import ingress-nginx verification tasks
  ansible.builtin.import_tasks: verify.yml
