---
- name: Gather system facts
  ansible.builtin.setup:

- name: Import Docker installation tasks
  ansible.builtin.import_tasks: install.yml

- name: Import Docker verification tasks
  ansible.builtin.import_tasks: verify.yml
