---
- name: Gather system facts
  ansible.builtin.setup:

- name: Import ArgoCD installation tasks
  ansible.builtin.import_tasks: install.yml

- name: Import ArgoCD verification tasks
  ansible.builtin.import_tasks: verify.yml

- name: Import ArgoCD application tasks
  ansible.builtin.import_tasks: application.yml

- name: Import ArgoCD ingress tasks
  ansible.builtin.import_tasks: ingress.yml
